travis:
  secure:
    BINSTAR_TOKEN: pvgzNpy6oaapzt/KfEQlaTQ3go/e79ThFGFnXp0xSwM8z0zJL46rWZNrXDWDg2c+7ffHUwmbxI4SuWx22F0M4zxaR32lwxgfjmBTUYwl/hOWmRq0ynqQPtcvKfdqyfINWfaX0nFKt94tjwdhq26QWXGcPoF5hsmpmSnnpN/brkNSv1hPF8eVrVwCCk71FYKc7aBWskZZ1VvQeUY7pP2XljzmycwpyDrucaQyps+wk0qJZ98Z2F2XRSSlWO1CTSKCg22B25THefmZxYXTadztL2cGI4Xhb7nbsFIdrMzRURKrnJ31TYEWUaZPcE21fnaMs4grqRFCCxRt0FJTtJ6fSHuXbp/0JN5OsL1DUkc6h7nVvVeKs+0yIruUjtv5N1JveuFAyQ1AStIZpranZ3eIdoOs+NJksGZ+up0BNsazyN3fMjyjsf+DdBrSht5EOYebqRMpgiarAIDKd46kghYLSPbfTch5UfEVw6I6p+llo8Qv0MH5/Gdy84RoxG5vNpQuuBhDvFn4DEk77DnMh8F5Sla4DQy228mJEugB2ct2iKxtL9csbD49ZE34Jv8Pd2f/o4+WqvLUIhJKkj4wK15/5A6l50s6nVk9JBhPICsQCX122vQvtw1Z8dIjEVxHkbbJTMeXOKAdl5pz2wwPv01wTaNbajcugfbnwBkckiDIrUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
